import 'dart:convert';
import 'package:flutter/material.dart';

/// Centralisateur de toutes les traductions de l'application
/// Utilisation: AppLocalizations.of(context).translate('clé')
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  /// Traductions regroupées par langue (fr / en)
  static final Map<String, Map<String, String>> _localizedValues = {
    'fr': {
      // Common
      'continue': 'Continuer',
      'health_connect_unavailable': 'Health Connect non disponible sur cet appareil.',
      'health_connect_required': 'Accès Health Connect requis. Vérifiez les paramètres de l\'appli Santé Connect ou relancez l\'application.',
      'back': 'Retour',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'done': 'Terminé',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'add_meal': 'Ajouter repas',
      'kcal': 'kcal',
      'unit_kcal': 'KCAL',
      'day': 'Jour',
      'week': 'Semaine',
      'month': 'Mois',
      'view_all': 'Tout afficher',
      'progress': 'PROGRESSION',
      'kcal_per_day': 'kcal/jour',
      'per_week': 'par semaine',
      'breakfast': 'Petit-déjeuner',
      'lunch': 'Déjeuner',
      'dinner': 'Dîner',
      'snack': 'Snack',
      'finish': 'Terminer',
      'required': 'Requis',
      'select': 'Sélectionner',
      'confirm': 'Confirmer',
      'saving': 'Enregistrement...',
      'composed_meal': 'Repas composé',
      'items_count': 'articles',
      'repas_unit': 'repas',
      'meal_unit': 'repas',

      // Days & Months
      'monday': 'Lundi', 'tuesday': 'Mardi', 'wednesday': 'Mercredi', 'thursday': 'Jeudi', 'friday': 'Vendredi', 'saturday': 'Samedi', 'sunday': 'Dimanche',
      'mon': 'LUN', 'tue': 'MAR', 'wed': 'MER', 'thu': 'JEU', 'fri': 'VEN', 'sat': 'SAM', 'sun': 'DIM',
      'january': 'Janvier', 'february': 'Février', 'march': 'Mars', 'april': 'Avril', 'may': 'Mai', 'june': 'Juin', 'july': 'Juillet', 'august': 'Août', 'september': 'Septembre', 'october': 'Octobre', 'november': 'Novembre', 'december': 'Décembre',
      'jan': 'JAN', 'feb': 'FÉV', 'mar': 'MAR', 'apr': 'AVR', 'may': 'MAI', 'jun': 'JUIN', 'jul': 'JUIL', 'aug': 'AOÛT', 'sep': 'SEP', 'oct': 'OCT', 'nov': 'NOV', 'dec': 'DÉC',
      'activity_history': 'Historique d\'activité',
      'select_label_desc': 'Choisissez l\'aliment qui correspond à votre photo',

      // Auth
      'login_title': 'Connexion',
      'login_subtitle': 'Gestion complète de votre santé',
      'email_label': 'Adresse e-mail',
      'email_hint': 'votre@email.com',
      'password_label': 'Mot de passe',
      'password_hint': '••••••••',
      'forgot_password': 'Mot de passe oublié ?',
      'login_button': 'Se connecter',
      'google_login': 'Continuer avec Google',
      'no_account': 'Vous n\'avez pas de compte ?',
      'signup_link': 'Inscrivez-vous',
      'email_required': 'E-mail requis',
      'email_invalid': 'E-mail invalide',
      'password_min': '7 caractères minimum',
      'back_to_login': 'Retour à la connexion',
      'new_user': 'Nouvel Utilisateur',
      'pwd_min_length': 'Au moins 7 caractères',
      'pwd_mixed_case': 'Majuscule et minuscule',
      'pwd_digit': 'Au moins un chiffre',
      'pwd_special': 'Caractère spécial (# & @ _ ! * \$ % .)',
      'signup_title': 'Inscription',
      'signup_header': 'Créer un compte',
      'confirm_password': 'Confirmer le mot de passe',
      'confirm_password_label': 'Confirmez le mot de passe',
      'passwords_dont_match': 'Les mots de passe ne correspondent pas',
      'already_have_account': 'Déjà un compte ?',
      'login_link': 'Se connecter',
      'signup_failed': 'Inscription échouée',
      'signup_subtitle': 'Commencez votre suivi de santé',
      'name_label': 'Nom complet',
      'name_hint': 'Jean Dupont',
      'name_required': 'Nom requis',
      'otp_resent': 'Nouveau code OTP envoyé !',
      'link_resent': 'Lien de vérification renvoyé !',
      'verify_email_title': 'Vérification email',
      'verify_email_header': 'Vérifiez votre email',
      'code_sent_to': 'Un code à 6 chiffres a été envoyé à\n',
      'link_sent_to': 'Un lien de vérification a été envoyé à\n',
      'i_verified': "J'ai vérifié mon email",
      'resend_in': 'Renvoyer dans ',
      'resend_code': 'Renvoyer le code',
      'resend_link': 'Renvoyer le lien',
      'forgot_password_title': 'Mot de passe oublié',
      'forgot_password_header': 'Réinitialiser le mot de passe',
      'forgot_password_desc': 'Entrez votre adresse e-mail et nous vous enverrons un code de vérification pour réinitialiser votre mot de passe.',
      'send_link': 'Envoyer le code',
      'back_to_login_btn': 'Retour à la connexion',
      'otp_sent_email': 'Code de vérification envoyé à votre adresse email.',
      'reset_password_title': 'Nouveau mot de passe',
      'reset_password_header': 'Créez votre nouveau mot de passe',
      'new_password_label': 'Nouveau mot de passe',
      'update_button': 'Mettre à jour',
      'passwords_mismatch': 'Les mots de passe ne correspondent pas',
      'email_missing_reset': 'E-mail manquant pour la réinitialisation',
      'password_updated': 'Mot de passe mis à jour avec succès !',
      'enter_code': 'Entrez le code de vérification',
      'reset_title': 'Vérification',
      'verify_code_button': 'Vérifier le code',

      // Goals & Profile Setup
      'goals_title': 'Vos Objectifs',
      'gender_title': 'Choisissez votre\nsexe',
      'gender_subtitle': 'Cela sera utilisé pour calibrer\nvotre plan personnalisé.',
      'birth_title': 'Quand etes-vous\nne(e) ?',
      'birth_subtitle': 'Cela sera pris en compte lors du calcul\nde vos objectifs nutritionnels quotidiens.',
      'female': 'Femme',
      'male': 'Homme',
      'goals_header': 'Quel est votre\nobjectif principal ?',
      'goals_subtitle': 'Sélectionnez les domaines sur lesquels vous souhaitez vous concentrer.',
      'weight_loss': 'Perte de poids',
      'weight_loss_desc': 'Réduire la masse grasse et habitudes durables',
      'muscle_gain': 'Prise de muscle',
      'muscle_gain_desc': 'Augmenter la force et le volume physique',
      'lifestyle': 'Vie Saine',
      'lifestyle_desc': 'Énergie et bien-être mental global',
      'skip': 'Passer',
      'fine_tune_goal': 'Affinez votre objectif',
      'adjust_metrics': 'Ajustez vos mesures pour personnaliser votre plan nutritionnel.',
      'height': 'Taille',
      'weight_current': 'Poids Actuel',
      'weight_target': 'Poids Cible',
      'health_diet_prefs': 'Santé & Préférences Alimentaires',
      'select_all_apply': 'Sélectionnez tout ce qui s\'applique à vous.',
      'conditions_label': 'CONDITIONS',
      'pathologies_label': 'PATHOLOGIES / CONDITIONS',
      'allergies_label': 'ALLERGIES',
      'goal_summary': 'Objectif : ',
      'reduce_weight': 'Réduire le poids de ',
      'gain_weight': 'Prendre du poids de ',
      'by': ' de ',
      'how_many_kg': 'Combien de kilos voulez-vous perdre ?',
      'choose_pace': 'Choisissez votre rythme',
      'pace_slow': 'Lent',
      'pace_steady': 'Régulier',
      'pace_fast': 'Rapide',
      'pace_desc': 'Un rythme régulier est plus durable pour la santé.',
      'pace_slow_steady': 'Lent et régulier',
      'pace_warning_fast': 'Vous pourriez vous sentir très fatigué et avoir la peau distendue',
      'recommended': 'Recommandé',
      'daily_forecast': 'Prévisions Quotidiennes',
      'forecast_desc': 'Basé sur votre rythme ',
      'daily_deficit': 'DÉFICIT QUOTIDIEN',
      'goal_date': 'DATE ESTIMÉE L\'OBJECTIF',
      'reach_goal_text_1': 'Pour atteindre ',
      'reach_goal_text_2': ' avec un rythme ',
      'reach_goal_text_3': ', vous terminerez votre objectif vers le ',
      'lose_weight_speed': 'Vitesse de perte de poids par semaine',

      // Plan & Habits
      'build_your_plan': 'Créez votre plan',
      'customize_plan_desc': 'Personnalisez votre entraînement pour calculer vos besoins nutritionnels.',
      'target_muscle_groups': 'Groupes musculaires ciblés',
      'full_body': 'Corps entier',
      'upper_body': 'Haut du corps',
      'legs': 'Jambes',
      'push_pull': 'Pousser / Tirer',
      'nutrition_focus': 'Focus Nutrition',
      'lean_bulk': 'Prise de masse sèche',
      'high_protein': 'Riche en protéines',
      'balanced': 'Équilibré',
      'weekly_training_days': 'Jours d\'entraînement par semaine',
      'days_per_week': 'jours/semaine',
      'training_frequency': 'Fréquence d\'entraînement',
      'training_days_count': '{count} jours',
      'growth_fuel': 'VOTRE CARBURANT CROISSANCE',
      'estimated_protein': 'Objectif estimé en protéines',
      'optimize_wellness': 'Optimiser le bien-être',
      'wellness_journey_desc': 'Sélectionnez les habitudes à suivre pour votre parcours santé.',
      'build_habits_title': 'Créez vos nouvelles habitudes',
      'build_habits_desc': 'Sélectionnez les habitudes quotidiennes sur lesquelles vous souhaitez vous concentrer.',
      'habit_water_title': 'Boire 2L d\'eau',
      'habit_water_desc': 'Booste l\'énergie et la santé de la peau',
      'habit_veggies_title': 'Manger plus de légumes',
      'habit_veggies_desc': 'Ajoutez 3 portions à vos repas quotidiens',
      'habit_processed_title': 'Moins de produits transformés',
      'habit_processed_desc': 'Privilégiez les aliments entiers et naturels',
      'habit_sleep_title': '7+ Heures de sommeil',
      'habit_sleep_desc': 'Optimise la récupération et la concentration',
      'habit_walk_title': '15 min de marche par jour',
      'habit_walk_desc': 'Un geste simple pour le cœur',
      'prepare_for_goal': 'Préparez-vous à atteindre votre objectif : {title}',
      'motto_weight_loss': 'Chaque petit pas compte vers un nouveau vous.',
      'motto_muscle_gain': 'La constance est la clé de la croissance.',
      'motto_lifestyle': 'Votre bien-être est une priorité, pas une option.',
      'motto_default': 'Définissez votre chemin vers la santé.',

      // Health Conditions & Allergies
      'diabetes_type_1_name': 'Diabète Type 1',
      'diabetes_type_1_desc': 'Nécessite une gestion de l\'insuline et une surveillance étroite du taux de sucre.',
      'diabetes_type_2_name': 'Diabète Type 2',
      'diabetes_type_2_desc': 'Peut être géré avec l\'alimentation, l\'exercice et des médicaments.',
      'obesity_name': 'Obésité',
      'obesity_desc': 'Excès de graisse corporelle augmentant les risques pour la santé.',
      'hypertension_name': 'Hypertension',
      'hypertension_desc': 'Pression artérielle élevée nécessitant moins de sel et des changements de vie.',
      'high_cholesterol_name': 'Cholestérol Élevé',
      'high_cholesterol_desc': 'Niveaux élevés pouvant mener à des maladies cardiaques.',
      'heart_disease_name': 'Maladie Cardiaque',
      'heart_disease_desc': 'Conditions affectant le cœur et la circulation sanguine.',
      'gerd_name': 'Reflux Gastrique (RGO)',
      'gerd_desc': 'L\'acide gastrique remonte dans l\'œsophage.',
      'ibs_name': 'Syndrome de l\'Intestin Irritable (SII)',
      'ibs_desc': 'Affecte la digestion et provoque des ballonnements.',
      'anemia_name': 'Anémie',
      'anemia_desc': 'Faible taux de fer provoquant fatigue et faiblesse.',
      'thyroid_name': 'Trouble de la Thyroïde',
      'thyroid_desc': 'Affecte le métabolisme et les niveaux d\'énergie.',
      'pcos_name': 'SOPK',
      'pcos_desc': 'Déséquilibre hormonal affectant la santé des femmes.',
      'none_condition_name': 'Aucune condition',
      'none_condition_desc': 'Aucun problème de santé spécifique.',
      'peanuts_name': 'Cacahuètes',
      'tree_nuts_name': 'Fruits à coque',
      'milk_name': 'Lait',
      'eggs_name': 'Œufs',
      'gluten_name': 'Gluten',
      'fish_name': 'Poisson',
      'shellfish_name': 'Crustacés',
      'soy_name': 'Soja',
      'sesame_name': 'Sésame',
      'lactose_intolerance_name': 'Intolérance au Lactose',
      'gluten_sensitivity_name': 'Sensibilité au Gluten',
      'no_allergies_name': 'Aucune allergie',
      'mild': 'Léger',
      'moderate': 'Modéré',
      'severe': 'Sévère',

      // Home & Dashboard
      'hi_name': 'Bonjour, {name} !',
      'dashboard_title': 'Tableau de Bord',
      'daily_nutrition': 'Nutrition du Jour',
      'daily_nutrition_status': 'État Nutritionnel du Jour',
      'in_progress': 'En cours',
      'calories_left': 'Kcal Restantes',
      'consumed': 'Consommé',
      'goal': 'Objectif',
      'ai_insights': 'Conseils IA',
      'quick_actions': 'Actions Rapides',
      'log_meal': 'Repas',
      'add_water': 'Ajouter 250ml',
      'log_activity': 'Activité',
      'todays_vitals': 'Vitaux du Jour',
      'steps': 'Pas',
      'sleep': 'Sommeil',
      'water': 'Eau',
      'hours': 'h',
      'minutes': 'm',
      'water_added': 'Eau ajoutée avec succès !',
      'nutrition_timeline': 'Chronologie Nutritionnelle',
      'now': 'MAINTENANT',
      'auto_synced': 'AUTO-SYNCÉ',
      'ready_for_meal': 'Prêt pour le déjeuner ?',
      'scan_meal_desc': 'Scannez votre repas pour un suivi instantané',
      'target_weight_with_current': 'Poids cible : {target}kg (Actuel : {current}kg)',

      // Insights
      'insights_title': 'Analyses Hebdomadaires',
      'nutritional_consistency': 'Cohérence Nutritionnelle',
      'loading_progression': 'Chargement des données...',
      'smart_insights': 'Analyses Intelligentes',
      'pro_tip': 'ASTUCE',
      'insight_hydration': 'Vous êtes en retard sur votre consommation d\'eau. Buvez de l\'eau pour maintenir votre efficacité métabolique.',
      'insight_sleep': 'Vous avez dormi moins de 6 heures. Le repos est crucial pour la récupération et la concentration.',
      'insight_protein': 'Votre apport en protéines est faible aujourd\'hui. Pensez à ajouter un repas riche en protéines.',
      'insight_positive': 'Beau travail ! Vous êtes sur la bonne voie avec vos objectifs de santé aujourd\'hui.',
      'insight_overeating': 'Vous avez dépassé votre objectif calorique quotidien de {diff} kcal.',
      'tip_protein_title': 'Boost de Protéines !',
      'tip_protein_desc': 'Vous avez consommé 20% de protéines en plus cette semaine ! Idéal pour la récupération musculaire.',
      'tip_hydration_title': 'Victoire de Régularité',
      'tip_hydration_desc': 'Vous avez atteint votre objectif d\'hydratation 5 jours de suite.',

      // Profile & Settings
      'profile_summary_title': 'Résumé du Profil',
      'premium_member': 'Membre Premium SantéSynchro',
      'my_plan': 'Mon Plan',
      'daily_targets': 'Objectifs Quotidiens',
      'energy': 'ÉNERGIE',
      'hydration': 'HYDRATATION',
      'macronutrients': 'MACRONUTRIMENTS',
      'carbs': 'Glucides',
      'protein': 'Protéines',
      'fats': 'Lipides',
      'health_diet': 'Santé & Régime',
      'settings_title': 'Réglages',
      'language': 'Langue',
      'logout': 'Se déconnecter',
      'delete_account': 'Supprimer le compte',
      'delete_confirm_desc': 'Êtes-vous sûr ? Cette action supprimera définitivement vos données.',
      'change_language': 'Changer la langue',
      'dark_mode': 'Mode Sombre',
      'edit_profile': 'Modifier le profil',
      'profile_updated': 'Profil mis à jour avec succès',
      'save_error': 'Erreur lors de la sauvegarde',
      'personal_info': 'INFORMATIONS PERSONNELLES',
      'full_name': 'Nom complet',
      'physical_measures': 'MESURES PHYSIQUES',
      'height_label_full': 'Taille',
      'weight_label_full': 'Poids',
      'confirm_start': 'Confirmer et Commencer',
      'none': 'Aucune préférence',

      // Meal Logging & Scanning
      'add_manual': 'Ajout Manuel',
      'search_hint': 'Rechercher un aliment...',
      'meal_type': 'TYPE DE REPAS',
      'total_energy': 'TOTAL ÉNERGIE',
      'remaining_budget': 'Budget restant',
      'proteins_label': 'PROTÉINES',
      'carbs_label': 'GLUCIDES',
      'fats_label': 'LIPIDES',
      'added_ingredients': 'INGRÉDIENTS AJOUTÉS',
      'add_another_ingredient': 'Ajouter un autre ingrédient',
      'add_to_journal': 'AJOUTER AU JOURNAL',
      'at_least_one_ingredient': 'Veuillez ajouter au moins un ingrédient',
      'meal_saved': 'Repas enregistré !',
      'add_ingredient': 'Ajouter l\'ingrédient',
      'smart_scan_title': 'Smart Scan IA',
      'ai_analyzing': 'Analyse par l\'IA...',
      'ai_estimation': 'Estimation IA',
      'take_photo': 'Prendre une photo',
      'pick_gallery': 'Choisir dans la galerie',
      'image_source': 'Source de l\'image',
      'camera': 'Caméra',
      'gallery': 'Galerie',
      'scan_photo_desc': 'Prenez une photo pour identifier\nvotre repas et ses calories',
      'ai_analysis_failed': 'Analyse impossible. Vérifiez votre connexion ou l\'image.',
      'meal_added_success': 'Repas ajouté avec succès !',
      'detected_meal': 'Repas détecté',
      'kcal_label': 'KCAL',
      'prot_label': 'PROT.',
      'carb_label': 'GLUC.',
      'fat_label': 'LIP.',
      'barcode_scanner_title': 'SCANNER CODE-BARRES',
      'align_barcode': 'ALIGNER LE CODE',
      'product_not_recognized': 'Produit non reconnu',
      'quantity_with_unit': 'Quantité ({unit})',
      'unknown_product': 'Produit inconnu',
      'search_ingredients_hint': 'Banane, Yaourt nature, Nutella...',
      'results_disclaimer': 'Résultats possibles — non garantis',
      'no_results_found': 'Aucun {mode} trouvé',
      'search_by_name': 'Recherchez un {mode}\npar son nom',
      'meal_singular': 'repas',
      'product_singular': 'produit',

      // Vitals Input
      'input_vitals': 'Saisir mes vitaux',
      'steps_label': 'Nombre de pas',
      'sleep_hours': 'Heures de sommeil',
      'sleep_minutes': 'Minutes',
      'vitals_saved': 'Vitaux enregistrés !',
      'steps_unit': 'pas',
      'sleep_recorded': 'de sommeil enregistrés',

      // Health Connect
      'health_connect_not_available': 'Health Connect non disponible sur cet appareil.',
      'health_connect_connected': 'Health Connect connecté.',
      'health_connect_denied': 'Accès Health Connect refusé.',
      'health_connect_busy': 'Demande d\'accès en cours...',
      'health_connect_sync': 'Synchronisation Android Health Connect',

      // Explanations
      'how_is_goal_calculated': 'Comment est calculé votre objectif ?',
      'bmr_explanation_1': 'Votre métabolisme de base (BMR) est de ',
      'bmr_explanation_2': '. Avec une activité ',
      'bmr_explanation_3': ', votre dépense totale est de ',
      'bmr_explanation_4': ' par jour.\nPour un objectif de ',
      'bmr_explanation_5': ', nous recommandons ',
    },
    'en': {
      // Common
      'continue': 'Continue',
      'back_to_login': 'Back to Login',
      'new_user': 'New User',
      'pwd_min_length': 'At least 7 characters',
      'pwd_mixed_case': 'Uppercase and lowercase',
      'pwd_digit': 'At least one digit',
      'pwd_special': 'Special character (# & @ _ ! * \$ % .)',
      'health_connect_unavailable': 'Health Connect not available on this device.',
      'health_connect_required': 'Health Connect access required. Check Health Connect app settings or restart the application.',
      'back': 'Back',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'save': 'Save',
      'cancel': 'Cancel',
      'done': 'Done',
      'edit': 'Edit',
      'delete': 'Delete',
      'add_meal': 'Add meal',
      'kcal': 'kcal',
      'unit_kcal': 'KCAL',
      'day': 'Day',
      'week': 'Week',
      'month': 'Month',
      'view_all': 'View All',
      'progress': 'PROGRESS',
      'kcal_per_day': 'kcal/day',
      'per_week': 'per week',
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'snack': 'Snack',
      'finish': 'Finish',
      'required': 'Required',
      'select': 'Select',
      'confirm': 'Confirm',
      'saving': 'Saving...',
      'composed_meal': 'Composed meal',
      'items_count': 'items',
      'repas_unit': 'meal',
      'meal_unit': 'meal',

      // Days & Months
      'monday': 'Monday', 'tuesday': 'Tuesday', 'wednesday': 'Wednesday', 'thursday': 'Thursday', 'friday': 'Friday', 'saturday': 'Saturday', 'sunday': 'Sunday',
      'mon': 'MON', 'tue': 'TUE', 'wed': 'WED', 'thu': 'THU', 'fri': 'FRI', 'sat': 'SAT', 'sun': 'SUN',
      'january': 'January', 'february': 'February', 'march': 'March', 'april': 'April', 'may': 'May', 'june': 'June', 'july': 'July', 'august': 'August', 'september': 'September', 'october': 'October', 'november': 'November', 'december': 'December',
      'oct': 'OCT', 'nov': 'NOV', 'dec': 'DEC',
      'activity_history': 'Activity History',
      'select_label_desc': 'Choose the food that matches your photo',

      // Auth
      'login_title': 'Login',
      'login_subtitle': 'Complete management of your health',
      'email_label': 'Email Address',
      'email_hint': 'your@email.com',
      'password_label': 'Password',
      'password_hint': '••••••••',
      'forgot_password': 'Forgot Password?',
      'login_button': 'Log In',
      'google_login': 'Continue with Google',
      'no_account': 'Don\'t have an account?',
      'signup_link': 'Sign Up',
      'email_required': 'Email required',
      'email_invalid': 'Invalid email',
      'password_min': '7 characters minimum',
      'login_failed': 'Login failed',
      'signup_title': 'Sign Up',
      'signup_header': 'Create an Account',
      'confirm_password': 'Confirm Password',
      'confirm_password_label': 'Confirm your password',
      'passwords_dont_match': 'Passwords do not match',
      'already_have_account': 'Already have an account?',
      'login_link': 'Log In',
      'signup_failed': 'Signup failed',
      'signup_subtitle': 'Start your health tracking',
      'name_label': 'Full Name',
      'name_hint': 'John Doe',
      'name_required': 'Name required',
      'otp_resent': 'New OTP code sent!',
      'link_resent': 'Verification link resent!',
      'verify_email_title': 'Email Verification',
      'verify_email_header': 'Verify your email',
      'code_sent_to': 'A 6-digit code has been sent to\n',
      'link_sent_to': 'A verification link has been sent to\n',
      'i_verified': 'I have verified my email',
      'resend_in': 'Resend in ',
      'resend_code': 'Resend code',
      'resend_link': 'Resend link',
      'forgot_password_title': 'Forgot Password',
      'forgot_password_header': 'Reset Your Password',
      'forgot_password_desc': 'Enter your email address and we will send you a verification code to reset your password.',
      'send_link': 'Send Code',
      'back_to_login_btn': 'Back to login',
      'otp_sent_email': 'Verification code sent to your email address.',
      'reset_password_title': 'New Password',
      'reset_password_header': 'Create your new password',
      'new_password_label': 'New password',
      'update_button': 'Update',
      'passwords_mismatch': 'Passwords do not match',
      'email_missing_reset': 'Missing email for reset',
      'password_updated': 'Password updated successfully!',
      'enter_code': 'Enter the verification code',
      'reset_title': 'Verification',
      'verify_code_button': 'Verify Code',

      // Goals & Profile Setup
      'goals_title': 'Your Goals',
      'gender_title': 'Choose your\nGender',
      'gender_subtitle': 'This will be used to calibrate your\ncustom plan.',
      'birth_title': 'When were you\nborn?',
      'birth_subtitle': 'This will be taken into account when\ncalculating your daily nutrition goals.',
      'female': 'Female',
      'male': 'Male',
      'goals_header': 'What is your\nmain goal?',
      'goals_subtitle': 'Select the areas you want to focus on.',
      'weight_loss': 'Weight Loss',
      'weight_loss_desc': 'Reduce body fat and sustainable habits',
      'muscle_gain': 'Muscle Gain',
      'muscle_gain_desc': 'Increase physical strength and volume',
      'lifestyle': 'Healthy Lifestyle',
      'lifestyle_desc': 'Energy and overall mental well-being',
      'skip': 'Skip',
      'fine_tune_goal': 'Fine-tune your goal',
      'adjust_metrics': 'Adjust your metrics to help us personalize your daily nutrition plan.',
      'height': 'Height',
      'weight_current': 'Current Weight',
      'weight_target': 'Target Weight',
      'health_diet_prefs': 'Health & Dietary Preferences',
      'select_all_apply': 'Select any that apply to you.',
      'conditions_label': 'CONDITIONS',
      'pathologies_label': 'HEALTH CONDITIONS',
      'allergies_label': 'ALLERGIES',
      'goal_summary': 'Goal: ',
      'reduce_weight': 'Reduce body weight by ',
      'gain_weight': 'Gain body weight by ',
      'by': ' by ',
      'how_many_kg': 'How many kilograms do you want to lose?',
      'choose_pace': 'Choose your preferred pace',
      'pace_slow': 'Slow',
      'pace_steady': 'Steady',
      'pace_fast': 'Fast',
      'pace_desc': 'A steady pace is generally the most sustainable for long-term health.',
      'pace_slow_steady': 'Slow and Steady',
      'pace_warning_fast': 'You may feel very tired and develop loose skin',
      'recommended': 'Recommended',
      'daily_forecast': 'Daily Forecast',
      'forecast_desc': 'Based on your pace ',
      'daily_deficit': 'DAILY DEFICIT',
      'goal_date': 'ESTIMATED GOAL DATE',
      'reach_goal_text_1': 'To reach ',
      'reach_goal_text_2': ' at a ',
      'reach_goal_text_3': ' pace, you will complete your goal around ',
      'lose_weight_speed': 'Lose weight speed per week',

      // Plan & Habits
      'build_your_plan': 'Build Your Plan',
      'customize_plan_desc': 'Customize your training focus and frequency to calculate your nutritional requirements.',
      'target_muscle_groups': 'Target Muscle Groups',
      'full_body': 'Full Body',
      'upper_body': 'Upper Body',
      'legs': 'Legs',
      'push_pull': 'Push / Pull',
      'nutrition_focus': 'Nutrition Focus',
      'lean_bulk': 'Lean Bulk',
      'high_protein': 'High Protein',
      'balanced': 'Balanced',
      'weekly_training_days': 'Weekly Training Days',
      'days_per_week': 'days/week',
      'training_frequency': 'Training Frequency',
      'training_days_count': '{count} days',
      'growth_fuel': 'YOUR GROWTH FUEL',
      'estimated_protein': 'Estimated Protein Target',
      'optimize_wellness': 'Optimize Wellness',
      'wellness_journey_desc': 'Select habits you\'d like to track or improve during your health journey.',
      'build_habits_title': 'Build your new habits',
      'build_habits_desc': 'Select the daily habits you\'d like to focus on for a healthier lifestyle.',
      'habit_water_title': 'Drink 2L Water',
      'habit_water_desc': 'Boost energy and skin health',
      'habit_veggies_title': 'Eat More Veggies',
      'habit_veggies_desc': 'Add 3 servings to your daily meals',
      'habit_processed_title': 'Reduce Processed Food',
      'habit_processed_desc': 'Focus on whole, natural ingredients',
      'habit_sleep_title': '7+ Hours of Sleep',
      'habit_sleep_desc': 'Optimize recovery and focus',
      'habit_walk_title': 'Daily 15min Walk',
      'habit_walk_desc': 'Simple movement for heart health',
      'prepare_for_goal': 'Get ready to reach your goal: {title}',
      'motto_weight_loss': 'Every small step counts towards a new you.',
      'motto_muscle_gain': 'Consistency is the key to growth.',
      'motto_lifestyle': 'Your well-being is a priority, not an option.',
      'motto_default': 'Define your path to health.',

      // Health Conditions & Allergies
      'diabetes_type_1_name': 'Diabetes Type 1',
      'diabetes_type_1_desc': 'Requires insulin management and careful monitoring of blood sugar levels.',
      'diabetes_type_2_name': 'Diabetes Type 2',
      'diabetes_type_2_desc': 'Can be managed with diet, exercise, and medication.',
      'obesity_name': 'Obesity',
      'obesity_desc': 'Excess body fat that increases health risks.',
      'hypertension_name': 'Hypertension',
      'hypertension_desc': 'High blood pressure requiring reduced salt intake and lifestyle changes.',
      'high_cholesterol_name': 'High Cholesterol',
      'high_cholesterol_desc': 'High levels of cholesterol that may lead to heart disease.',
      'heart_disease_name': 'Heart Disease',
      'heart_disease_desc': 'Conditions affecting heart function and blood circulation.',
      'gerd_name': 'Acid Reflux (GERD)',
      'gerd_desc': 'Causes stomach acid to flow back into the esophagus.',
      'ibs_name': 'Irritable Bowel Syndrome (IBS)',
      'ibs_desc': 'Affects digestion and causes discomfort and bloating.',
      'anemia_name': 'Anemia',
      'anemia_desc': 'Low iron levels causing fatigue and weakness.',
      'thyroid_name': 'Thyroid Disorder',
      'thyroid_desc': 'Affects metabolism and energy levels.',
      'pcos_name': 'PCOS',
      'pcos_desc': 'Hormonal imbalance affecting women’s health.',
      'none_condition_name': 'No condition',
      'none_condition_desc': 'No specific health condition.',
      'peanuts_name': 'Peanuts',
      'tree_nuts_name': 'Tree Nuts',
      'milk_name': 'Milk',
      'eggs_name': 'Eggs',
      'gluten_name': 'Gluten',
      'fish_name': 'Fish',
      'shellfish_name': 'Shellfish',
      'soy_name': 'Soy',
      'sesame_name': 'Sesame',
      'lactose_intolerance_name': 'Lactose Intolerance',
      'gluten_sensitivity_name': 'Gluten Sensitivity',
      'no_allergies_name': 'No allergies',
      'mild': 'Mild',
      'moderate': 'Moderate',
      'severe': 'Severe',

      // Home & Dashboard
      'hi_name': 'Hi, {name}!',
      'dashboard_title': 'Dashboard',
      'daily_nutrition': 'Daily Nutrition',
      'daily_nutrition_status': 'Daily Nutrition Status',
      'in_progress': 'In Progress',
      'calories_left': 'Kcal Left',
      'consumed': 'Consumed',
      'goal': 'Goal',
      'ai_insights': 'AI Insights',
      'quick_actions': 'Quick Actions',
      'log_meal': 'Log Meal',
      'add_water': 'Add 250ml',
      'log_activity': 'Activity',
      'todays_vitals': 'Today\'s Vitals',
      'steps': 'Steps',
      'sleep': 'Sleep',
      'water': 'Water',
      'hours': 'h',
      'minutes': 'm',
      'water_added': 'Water added successfully!',
      'nutrition_timeline': 'Nutrition Timeline',
      'now': 'NOW',
      'auto_synced': 'AUTO-SYNCED',
      'ready_for_meal': 'Ready for Lunch?',
      'scan_meal_desc': 'Scan your meal for instant macro tracking',
      'target_weight_with_current': 'Target weight: {target}kg (Current: {current}kg)',

      // Insights
      'insights_title': 'Weekly Insights',
      'nutritional_consistency': 'Nutritional Consistency',
      'loading_progression': 'Loading progression data...',
      'smart_insights': 'Smart Insights',
      'pro_tip': 'PRO TIP',
      'insight_hydration': 'You\'re behind on water intake. Drink some water to maintain metabolic efficiency.',
      'insight_sleep': 'You slept less than 6 hours. Rest is crucial for recovery and focus.',
      'insight_protein': 'Your protein intake is low today. Consider adding a high-protein meal.',
      'insight_positive': 'Great job! You\'re on track with your health goals today.',
      'insight_overeating': 'You\'ve exceeded your daily calorie goal by {diff} kcal.',
      'tip_protein_title': 'Protein Power-Up!',
      'tip_protein_desc': 'You ate 20% more protein this week compared to last! Great for muscle recovery.',
      'tip_hydration_title': 'Consistency Win',
      'tip_hydration_desc': 'You hit your hydration goal 5 days in a row.',

      // Profile & Settings
      'profile_summary_title': 'Profile Summary',
      'premium_member': 'SantéSynchro Premium Member',
      'my_plan': 'My Plan',
      'daily_targets': 'Daily Targets',
      'energy': 'ENERGY',
      'hydration': 'HYDRATION',
      'macronutrients': 'MACRONUTRIENTS',
      'carbs': 'Carbs',
      'protein': 'Protein',
      'fats': 'Fats',
      'health_diet': 'Health & Diet',
      'settings_title': 'Settings',
      'language': 'Language',
      'logout': 'Log Out',
      'delete_account': 'Delete Account',
      'delete_confirm_desc': 'Are you sure? This action will permanently delete your data.',
      'change_language': 'Change Language',
      'dark_mode': 'Dark Mode',
      'edit_profile': 'Edit Profile',
      'profile_updated': 'Profile updated successfully',
      'save_error': 'Error during save',
      'personal_info': 'PERSONAL INFORMATION',
      'full_name': 'Full Name',
      'physical_measures': 'PHYSICAL MEASURES',
      'height_label_full': 'Height',
      'weight_label_full': 'Weight',
      'confirm_start': 'Confirm and Start',
      'none': 'No preference',

      // Meal Logging & Scanning
      'add_manual': 'Manual Add',
      'search_hint': 'Search for food...',
      'meal_type': 'MEAL TYPE',
      'total_energy': 'TOTAL ENERGY',
      'remaining_budget': 'Remaining budget',
      'proteins_label': 'PROTEINS',
      'carbs_label': 'CARBS',
      'fats_label': 'FATS',
      'added_ingredients': 'ADDED INGREDIENTS',
      'add_another_ingredient': 'Add another ingredient',
      'add_to_journal': 'ADD TO JOURNAL',
      'at_least_one_ingredient': 'Please add at least one ingredient',
      'meal_saved': 'Meal recorded!',
      'add_ingredient': 'Add ingredient',
      'smart_scan_title': 'AI Smart Scan',
      'ai_analyzing': 'AI is analyzing...',
      'ai_estimation': 'AI Estimation',
      'take_photo': 'Take a photo',
      'pick_gallery': 'Pick from gallery',
      'image_source': 'Image Source',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'scan_photo_desc': 'Take a photo to identify\nyour meal and its calories',
      'ai_analysis_failed': 'Analysis failed. Check your connection or the image.',
      'meal_added_success': 'Meal added successfully!',
      'detected_meal': 'Detected meal',
      'kcal_label': 'KCAL',
      'prot_label': 'PROT.',
      'carb_label': 'CARBS',
      'fat_label': 'FATS',
      'barcode_scanner_title': 'BARCODE SCANNER',
      'align_barcode': 'ALIGN THE CODE',
      'product_not_recognized': 'Product not recognized',
      'quantity_with_unit': 'Quantity ({unit})',
      'unknown_product': 'Unknown product',
      'search_ingredients_hint': 'Banana, Plain yogurt, Nutella...',
      'results_disclaimer': 'Possible results — not guaranteed',
      'no_results_found': 'No {mode} found',
      'search_by_name': 'Search for a {mode}\nby its name',
      'meal_singular': 'meal',
      'product_singular': 'product',

      // Vitals Input
      'input_vitals': 'Input Vitals',
      'steps_label': 'Number of steps',
      'sleep_hours': 'Sleep hours',
      'sleep_minutes': 'Minutes',
      'vitals_saved': 'Vitals recorded!',
      'steps_unit': 'steps',
      'sleep_recorded': 'of sleep recorded',

      // Health Connect
      'health_connect_not_available': 'Health Connect not available on this device.',
      'health_connect_connected': 'Health Connect connected.',
      'health_connect_denied': 'Health Connect access denied.',
      'health_connect_busy': 'Requesting access...',
      'health_connect_sync': 'Android Health Connect Sync',

      // Explanations
      'how_is_goal_calculated': 'How is your goal calculated?',
      'bmr_explanation_1': 'Your basal metabolic rate (BMR) is ',
      'bmr_explanation_2': '. With an activity level of ',
      'bmr_explanation_3': ', your total daily energy expenditure is ',
      'bmr_explanation_4': ' per day.\nFor a goal of ',
      'bmr_explanation_5': ', we recommend ',
    },
  };

  /// Récupère la traduction pour une clé donnée
  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  /// Délégué pour charger les localisations
  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'fr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
